--- #YAML:1.0
name: Mail-TempAddress
version: 0.60
author:
  - chromatic, C<chromatic@wgz.org>.
abstract: |-
  module for managing simple, temporary mailing addresses
license: perl
requires:
  Class::Roles: 0.30
  Email::Address: ''
  Mail::Action: 0.30
  YAML: 0.35
build_requires:
  Test::Exception: ''
  Test::MockObject: 0.11
  Test::Simple: 0.47
provides:
  Mail::TempAddress:
    file: lib/Mail/TempAddress.pm
    version: 0.60
  Mail::TempAddress::Address:
    file: lib/Mail/TempAddress/Address.pm
  Mail::TempAddress::Addresses:
    file: lib/Mail/TempAddress/Addresses.pm
generated_by: Module::Build version 0.25
